config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'maps/index'

  root 'static_pages#home'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/test_login', to: 'users#test_login'
  post '/posts', to: 'posts#confirm'
  post '/post/create', to: 'posts#create'
  get 'post/:id', to: 'posts#show'
  get '/map', to: 'posts#map'
  resources :maps, only: %i[index create]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :posts do
    resources :likes, only: %i[destroy create]
  end
  resources :relationships, only: %i[create destroy]
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @post = current_user.posts.build
      posts = Post.new
      posts = Post.all
      @user = current_user
      @myfeed_items = current_user.myfeed.paginate(page: params[:myfeed_items_page], per_page: 3)
      @followingfeed_items = current_user.followingfeed.paginate(page: params[:followingfeed_items_page], per_page: 3)
      @likingfeed_items = current_user.likingfeed.paginate(page: params[:likingfeed_items_page], per_page: 3)
    end
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
  def home; end
end

app/views/static_pages/_confirm.html.erb
     <div class="title"><p>投稿確認画面</p></div>
<%= form_for @post, url:'/post/create' do |f|%> 
  <table class="table">
    <tr>
      <th>カフェの名前</th>
      <td>
        <%= @post.store_name %>
        <%= f.hidden_field :store_name %>
      </td>
    </tr>
    <tr>
      <th>住所</th>
      <td>
        <%= @post.address_prefectures %>
        <%= f.hidden_field :address_prefectures %>
        <%= @post.address %>
        <%= f.hidden_field :address %>
      </td>
    </tr>
    <tr>
      <th>カフェの画像</th>
      <td>
        <%= image_tag @post.image.url, :size =>'300x250'%>
                <%= f.hidden_field :image_cache %>
      </td>
    </tr>
            <tr>
      <th>営業時間</th>
      <td>
        <%= @post.time_start %>
        <%= f.hidden_field :time_start %>
        〜
        <%= @post.time_end %>
        <%= f.hidden_field :time_end %>
      </td>
    </tr>
        <tr>
      <th>環境</th>
      <td>
<% if @post.wifi.present? %>
 <%= image_tag 'wifi.png' , :size => '50x40'%>
 <%= f.hidden_field :wifi %>
<%end%>

<% if @post.plug.present? %>
 <%= image_tag 'plug.png' , :size => '50x40'%>
 <%= f.hidden_field :plug %>
<%end%>

<% if @post.tabacco.present? %>
 <%= image_tag 'tabacco.png' , :size => '50x40'%>
 <%= f.hidden_field :tabacco %>
<%end%>

<% if @post.card.present? %>
 <%= image_tag 'card.png' , :size => '50x40'%>   
 <%= f.hidden_field :card %>
<%end%>
      </td>
    </tr>
      <tr>
      <th>評価</th>
      <td>
<% if @post.evaluation1.present? %>
 <%= image_tag 'star.png' , :size => '50x40'%>
 <%= f.hidden_field :evaluation1 %>
<%end%>

<% if @post.evaluation2.present? %>
 <%= image_tag 'star.png' , :size => '50x40'%>
 <%= f.hidden_field :evaluation2 %>
<%end%>

<% if @post.evaluation3.present? %>
 <%= image_tag 'star.png' , :size => '50x40'%>
 <%= f.hidden_field :evaluation3 %>
<%end%>

<% if @post.evaluation4.present? %>
 <%= image_tag 'star.png' , :size => '50x40'%>
 <%= f.hidden_field :evaluation4 %>
<%end%>

<% if @post.evaluation5.present? %>
 <%= image_tag 'star.png' , :size => '50x40'%>
 <%= f.hidden_field :evaluation5 %>
<%end%>
      </td>
    </tr>
    </tr>
  </table>
<%= f.submit '投稿する'%>
<% end %>
<%= form_for(@post, url: new_post_path, html: {method: 'GET'}) do |f|%>
        <%= f.hidden_field :store_name %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :address_prefectures %>
        <%= f.hidden_field :image_cache %>
        <%= f.hidden_field :time_start %>
        <%= f.hidden_field :time_end %>
        <%= f.hidden_field :wifi %>
        <%= f.hidden_field :plug %>
        <%= f.hidden_field :tabacco %>
        <%= f.hidden_field :card %>
        <%= f.hidden_field :evaluation1 %>
        <%= f.hidden_field :evaluation2 %>
        <%= f.hidden_field :evaluation3 %>
        <%= f.hidden_field :evaluation4 %>
        <%= f.hidden_field :evaluation5 %>
<%= f.submit '入力画面に戻る'%>
<% end %>

app/views/static_pages/_edit.html.erb
  <div class="title"><p>投稿編集画面</p></div>
    <%= form_for(@post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class="edit_detail">

      <%= f.label :名前 %>
      <%= f.text_field :store_name, class: 'form-control' %>

      <%= f.label :住所 %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :カフェの画像 %>
      <%= f.file_field :image, class: 'form-control' %>

<div class="store_time">
      <%= f.label :営業時間 %>
      <%= f.time_field :time_start, class: 'form-control' %>
      <%= f.label :"〜" %>
      <%= f.time_field :time_end, class: 'form-control' %>
</div>

<%= f.label :"環境" %>
<div class="environment center">
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default" >
        <%= f.check_box :wifi, {} , true, false %><%= image_tag 'wifi.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
        <%= f.check_box :plug , {} , true, false %><%= image_tag 'plug.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
        <%= f.check_box :tabacco , {} , true, false %><%= image_tag 'tabacco.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
        <%= f.check_box :card , {} , true, false %><%= image_tag 'card.png' , :size => '50x40'%>
    </label>
</div>
</div>

<%= f.label :"評価" %>
<div class="evaluation center">

<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
         <%= f.check_box :evaluation1,   {} , '1', nil %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
         <%= f.check_box :evaluation2,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
         <%= f.check_box :evaluation3,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
  		 <%= f.check_box :evaluation4,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
  		 <%= f.check_box :evaluation5,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
</div>

      <%= f.submit "変更する", class: "btn btn-primary" %>
</div>
</div>
<% end %>

app/views/static_pages/_new.html.erb
<div class="title"><p>投稿画面</p></div>
<%= form_for @post  do |form| %>
<%= render 'shared/error_messages', object: form.object %>

<%= form.label :"カフェ" %> <%= form.text_field :store_name, id: :store_name ,class: "form-control",placeholder: "カフェの名前をご入力ください"%>
<%= form.label :"住所" %><%= form.select :address_prefectures, ["北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県", "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"], {prompt: '都道府県を選択してください'}, class: 'form-control btn' %>


<%= form.text_field :address, id: :address ,class: "form-control",placeholder: "住所をご入力ください"%>

<%= form.label :"カフェの画像" %><%= form.file_field :image %>                       

<div class="store_time">
<%= form.label :"営業時間"%>
<%= form.time_field :time_start ,class: "form-control"%> <%= form.label :"〜" %> <%= form.time_field :time_end ,class: "form-control"%>
</div>

<%= form.label :"環境" %>
<div class="environment center" data-toggle="tooltip" title="Wi-Fi,充電,喫煙,クレジットカードの利用状況をご入力ください">
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default" >
        <%= form.check_box :wifi, {} , true, false %><%= image_tag 'wifi.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
        <%= form.check_box :plug , {} , true, false %><%= image_tag 'plug.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
        <%= form.check_box :tabacco , {} , true, false %><%= image_tag 'tabacco.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
        <%= form.check_box :card , {} , true, false %><%= image_tag 'card.png' , :size => '50x40'%>
    </label>
</div>
</div>

<%= form.label :"評価" %>
<div class="evaluation center">

<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
         <%= form.check_box :evaluation1,   {} , '1', nil %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
         <%= form.check_box :evaluation2,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
         <%= form.check_box :evaluation3,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
  		 <%= form.check_box :evaluation4,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-default">
  		 <%= form.check_box :evaluation5,  {} , '1', nil  %><%= image_tag 'star.png' , :size => '50x40'%>
    </label>
</div>
</div>

<%= form.submit "投稿" %>
</div>
<% end %>

app/views/static_pages/home.html.erb
 <% if logged_in? %> 

  <div class="row">
 <%= render 'shared/messages'%>
    <div class="col-md-3">
      <section class="user_info">
        <%= render 'shared/user_info' %>
        <%= render 'shared/follow_form' if logged_in? %>
      </section>
    </div>

    <div class="col-md-9">

      <p class="my_toptitle">投稿したカフェ</p>
      <%= render 'shared/myfeed' %>
                <p class="like_toptitle">いいねしたカフェ</p>
      <%= render 'shared/likingfeed' %>
      <p class="following_toptitle">フォロワーの投稿したカフェ</p>
    　<%= render 'shared/followingfeed' %>


    </div>

  </div>
<% else %>
 <div class="image">
　<%= render 'shared/messages'%>
　<div class="home_topic">
  <div class="home_topic_title">
   <h1>お気に入りのカフェを投稿しよう</h1>
  </div>

  <div class="home_topic_detail">
   <h2>
    自分のお気に入りのカフェを投稿で共有するアプリケーションです。<br>
    住所や営業時間はもちろん、Wi-Fiやクレジットカードの利用状況まで確認いただきます。<br>
    また、Google Mapを用いて住所情報から場所を特定することも可能です。
   </h2>
   </div>
 </div>
 <div class="home_loginbutton">
   <%= link_to "サインアップ", signup_path, class: "btn" %>
   <%= link_to 'テストログイン', test_login_path, class:"btn" %> 
 </div>
</div>
<% end %>