config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'maps/index'

  root 'static_pages#home'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/test_login', to: 'users#test_login'
  post '/posts', to: 'posts#confirm'
  post '/post/create', to: 'posts#create'
  get 'post/:id', to: 'posts#show'
  get '/map', to: 'posts#map'
  resources :maps, only: %i[index create]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :posts do
    resources :likes, only: %i[destroy create]
  end
  resources :relationships, only: %i[create destroy]
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  protect_from_forgery except: %i[create destroy]
  before_action :set_post
  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: params[:post_id])
    like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.erb
<% if @post.liked_by?(current_user) %>
<%= button_to 'いいね解除', post_like_path(@post, Like.find_by(post: @post, user: current_user)), method: :delete, remote: true %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post), method: :post, remote: true %>
<% end %>

app/views/likes/create.js.erb
$('.like_button').html("<%= j(render 'likes/like' , post: @post) %>");

app/views/likes/destroy.js.erb
$('.like_button').html("<%= j(render 'likes/like' , post: @post) %>");