config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'maps/index'

  root 'static_pages#home'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/test_login', to: 'users#test_login'
  post '/posts', to: 'posts#confirm'
  post '/post/create', to: 'posts#create'
  get 'post/:id', to: 'posts#show'
  get '/map', to: 'posts#map'
  resources :maps, only: %i[index create]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :posts do
    resources :likes, only: %i[destroy create]
  end
  resources :relationships, only: %i[create destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>つ間違っている箇所があります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<!-- フォローボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow_form.html.erb
<%unless @user == current_user%>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "shared/unfollow", user: @user %>
    <% else %>
      <%= render "shared/follow" , user: @user %>
    <% end %>
  </div>
<%end%>
<div><%=simple_format(@user.self_introduction)%></div>

app/views/shared/_followingfeed.html.erb
<% if @followingfeed_items.any? %>
  <ol class="Posts">
    <%= render @followingfeed_items %>
  </ol>
  <%= will_paginate @followingfeed_items, previous_label: '&lt 前へ', next_label: '次へ &gt', :param_name => 'followingfeed_items_page', class: "center" %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p class="footer__item">&copy;2020 COFFEEAPP</p>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container_header">
    <%= link_to "coffee app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "トップ", root_path %></li>
         <li><%= link_to "マップから探す", map_path%></li>
        <li><%= link_to "投稿一覧", posts_path%></li>
        <li><%= link_to "すべてのユーザー", users_path%></li>
        <% if logged_in? %>
          <li><%= link_to "投稿", new_post_path%></li> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              ユーザー情報 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user%></li> 
              <li><%= link_to "設定", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>

    </nav>

  </div>
</header>

app/views/shared/_infowindow.html.erb
<%= link_to post_path(post) do %>
  <div><%= image_tag post.image, :size => '100x100'%></div>
    <div><h4><%= post.store_name %></h4></div>
<% end %>

app/views/shared/_likingfeed.html.erb
<% if @likingfeed_items.any? %>
  <ol class="Posts">
         <% @likingfeed_items.each do |like| %>
         <% post = Post.find_by(id: like.post_id) %>
  <li>
   <a href="/post/<%= post.id%>"> 
   <div class="Post_detail">
<div class="Post_image_content">

     <div class="Post_image">
     <%= image_tag post.image, :size =>'100x100'%> 
     </div>
     <div class="Post_content">
     <p><strong>お店の名前</strong><span><%= post.store_name%></span></p> 
     <p><strong>住所 </strong><span><%= post.address_prefectures%></span></p>
     <p><strong>営業時間 </strong><span><%= post.time_start%>〜<%= post.time_end%></span></p> 
     </div>
</div>
     <span class="timestamp">
      <%= time_ago_in_words(post.created_at)%>前の投稿
      <% if current_user?(post.user) %>
       <%= link_to "削除", post, method: :delete,
                                       data: { confirm: "本当に削除してもよろしいでしょうか。" },class: "delete-link" %> 
      <% end %>
     </span>
    <% end %>

   </a>
  </li>


 </ol>
       <%= will_paginate @likingfeed_items, previous_label: '&lt 前へ', next_label: '次へ &gt', :param_name => 'likingfeed_items_page', class: "center" %>
<% end %>

app/views/shared/_messages.html.erb
       <% flash.each do |message_type, message| %>
      <div class="message">
        <div class="alert alert-<%= message_type%>"><%= message%></div>
        </div>
       <% end %>

app/views/shared/_myfeed.html.erb
<% if @myfeed_items.any? %>
  <ol class="Posts">
    <%= render @myfeed_items %>
    </ol>
      <%= will_paginate @myfeed_items, previous_label: '&lt 前へ', next_label: '次へ &gt', :param_name => 'myfeed_items_page', class: "center" %>
<% end %>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="mystats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>フォロー
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>フォロワー
    </strong>
  </a>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= image_tag @user.image.url ,class: 'userinfo_image', size: '200x200' %>
<div class="name"><%= @user.name</div> %>
<% @user ||= current_user %>
<div class="mystats">
  <a href="<%= following_user_path(@user)%>"> 
    <strong id="following" class="stat">
       <%= @user.following.count %>フォロー 
    </strong>
   </a>
  <a href="<%= followers_user_path(@user) %>%"> 
    <strong id="followers" class="stat">
      <%= @user.followers.count%>フォロワー 
    </strong>
  </a>
</div>